version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-travel-planner-frontend
    ports:
      - "80:80"
    environment:
      # Supabase Configuration (Required)
      # Set these in a .env file or export them before running docker-compose
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: unless-stopped
    networks:
      - ai-travel-network
    labels:
      - "com.ai-travel-planner.description=AI Travel Planner Frontend"

networks:
  ai-travel-network:
    driver: bridge
